services:
  - type: static
    name: ayurmed
    buildCommand: npm install && npm run build
    staticPublishPath: ./dist
    envVars:
      - key: API_KEY
        scope: build
        sync: false
